version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "0:0"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=1y
    ports:
      - '9090:9090'
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=<ISI USERNAME>
      - GF_SECURITY_ADMIN_PASSWORD=<ISI PASSWORD>
    restart: always

volumes:
  prometheus-data:
